# Site settings
title: Portfolio Michael Schouman
name: Michael Schouman
job_title: Interactieve Media Professional
email: michael@schouman.info
url: "http://www.schouman.info"
twitter_username: metalmini
github_username:  metalmini
linkedin_username:  michaelschouman

# Build settings
markdown: kramdown
